import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "LJM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
